### ISSUE TITLE
files for studios 

### ISSUE THREAD

**Issue by dontspamm** [MediaBrowser/Emby.Resources#166]
so placing the images into the metadata folder does not work 

the folder netflix has 2 images but none of them are picked by emby

is there anything that needs to be done to be automatically picked by emby ?

**Comment by LukePulverenti** [comment]
Hi, this is a place for people to contribute images, not for technical support. I would see here:

http://emby.media/community/index.php?/topic/739-how-to-report-a-problem/

Thanks.
